name = "redmonkye/glue"
version = "0.1.0-rc.3"
license = "MIT"
authors = ["afrxo"]
description = "A composition framework."
repository = "https://github.com/redmonkye/glue"
includes = [
    "LICENSE",
    "README.md",
    "pesde.toml",
    "src/init.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src/init.luau"]

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
